### ISSUE TITLE
Balloon Game

### ISSUE THREAD

**Issue by Hippopotomonstrosesquippedaliophobia** [LostIncorporated/Animo#10]
On loading the balloon game, in overlay if you spam home button it will eventually take you home. Didn't try but im guessing on loading the timer, when you click home it doesnt stop that and reset it, only after it has begun. 

Suggested fix, (easy fix) would be disable home/ esc home in that moment til it starts officially

**Comment by RedZelios** [comment]
Bug S Q U A S H E D *all hail the bug squasher* HAIL HAIL HAIL
