### ISSUE TITLE
Wall Building Game

### ISSUE THREAD

**Issue by Hippopotomonstrosesquippedaliophobia** [LostIncorporated/Animo#11]
The math breaks down after getting farther into the game, the fractions presented and options presented are not the same and you cannot progress after a while since the answers don't match etc.

**Comment by RedZelios** [comment]
Bug SQQUUUUAAASSSHHHHEEEDDDD *flosses*

**Comment by Hippopotomonstrosesquippedaliophobia** [comment]
I hope you are working on that assignment now and not coding sirrrr
